### ISSUE TITLE
Issues installing the theme.

### ISSUE THREAD

**Issue by sebben-blip** [Sped0n/bridget#169]
Hello I am getting some errors when I am trying to install the theme.

`Start building sites … 
hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended darwin/arm64 BuildDate=2023-11-08T11:18:07Z VendorInfo=brew

ERROR render of "page" failed: execute of template failed: template: _default/single.html:4:45: executing "main$htmltemplate_stateHTMLCmt" at <{{template "main$htmltemplate_stateHTMLCmt" .}}>: exceeded maximum template depth (100000)
ERROR render: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:4:45: executing "main$htmltemplate_stateHTMLCmt" at <{{template "main$htmltemplate_stateHTMLCmt" .}}>: exceeded maximum template depth (100000)
Built in 135 ms
Error: error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss): "/Users/macstudio/hugo/quick/themes/bridget/assets/scss/style.scss:10:1": File to import not found or unreadable: node_modules/swiper/swiper.scss.`

I have tried to install Swiper with NPM but it still does not work. What could be going wrong?

I have also made a thread on the Hugo forum.

https://discourse.gohugo.io/t/error-building-site-tocss-failed-to-transform-scss-style-scss-text-x-scss/47210

Any help would be appreciated as this is an awesome theme!

**Comment by Sped0n** [comment]
One possible guess here, have you set the [bundled](https://github.com/Sped0n/bridget/blob/2c8db4abe1157be6e966a43cde5286d848d8e88f/exampleSite/config/_default/params.toml#L6) to `true`? 

If you don't want to modify the theme, just set it to true, there is no need for `npm install`.

**Comment by sebben-blip** [comment]
I fixed it.

I downloaded node_modules and added it to the themes scss folder. Then it was able to build. Hope it helps someone.

**Comment by diwahsap** [comment]
@sebben-blip i get the same error. I tried your advice, and boom, well done!
