### ISSUE TITLE
doc: guide user to config part in installation doc

### ISSUE THREAD

**Issue by Sped0n** [Sped0n/bridget#228]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
`getStarted.md`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by maacumba** [comment]
Dear Sped0n,
thank you very much for making this theme available.

I was trying to install it today, but unfortunately I haven't managed to make it work.

I think it would be good to mention Node and NPM in the requirements .

I didn't install as a module. 

After git-cloning, I moved the folders under "exempleSite" to the project root.

"npm install" inside the theme/bridget folder.

When "hugo server", I get an error:

Built in 213 ms
Error: error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss): "/home/maacumba/Documents/Site_Offline/raio_studio/themes/bridget/assets/scss/style.scss:10:1": File to import not found or unreadable: node_modules/swiper/swiper.scss.

Thank you very much.

**Comment by Sped0n** [comment]
Will look into it as soon as I can, quite busy with exams now😭.

You can try to copy the `node_modules` to the project root, this should be the temporary fix. Or just set `bundled` option to true, so bridget will not try to build these artifacts itself.

**Comment by maacumba** [comment]
Great,
Moving the node_modules did the trick for testing. I will continue with the other instructions to change the styles.

Thank you for the prompt reply :)
Good lucky with exams.
