### ISSUE TITLE
Navigation enhancment

### ISSUE THREAD

**Issue by kyber-6** [Sped0n/bridget#347]
### Requirement

Allow for navigating between pictures with the arrow keys after expanding them.

### Suggested implements

-

### Verify steps

- [ ] Pull request is welcome. Check this if you want to start a pull request
- [X] I have searched on [Issue Tracker](https://github.com/Sped0n/bridget/issues), No duplicate or related open issue has been found
- [X] Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request

**Comment by kyber-6** [comment]
Additionally, you should be able to exit the expanded view using the ESC key.

**Comment by Sped0n** [comment]
https://github.com/Sped0n/bridget/blob/fb498971c7eb52738543a7f00f8fa07a8e731a17/assets/ts/desktop/stageNav.tsx#L66C1-L71C4

It is already implemented, may I ask what browser(and its version) do you use?

**Comment by kyber-6** [comment]
I am using Safari Version 17.5.

**Comment by Sped0n** [comment]
Can confirm, I will transfer this topic to another issue.

**Comment by Sped0n** [comment]
@kyber-6 now should be okay, if the problem persists you can reopen the issue at any time.

**Comment by Sped0n** [comment]
@kyber-6 pr #356 should do the job, can you confirm that the feature is working properly?

**Comment by kyber-6** [comment]
@Sped0n Now it is working perfectly, thanks!
