### ISSUE TITLE
Include GoatCounter Analytics

### ISSUE THREAD

**Issue by zirdl** [Sped0n/bridget#383]
### Requirement

Apart from the already included web analytics services, I think it might also be worth adding [GoatCounter](https://www.goatcounter.com/help/start)

### Suggested implements

Having GoatCounter analytics with bridget will help a lot to those who are starting out.

```
[analytics.goatcounter]
code = "goatcounter_code"
```

### Verify steps

- [ ] Pull request is welcome. Check this if you want to start a pull request
- [X] I have searched on [Issue Tracker](https://github.com/Sped0n/bridget/issues), No duplicate or related open issue has been found
- [X] Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request

**Comment by Sped0n** [comment]
Don't have a proper backend to test it, if more people request this I might give it a try

Pull request is welcomed

For now, you can just add your analytic script tag in head section of [baseof.html](https://github.com/Sped0n/bridget/blob/main/layouts/_default/baseof.html)
