### ISSUE TITLE
 标题

### ISSUE THREAD

**Issue by taochenjing** [Sped0n/bridget#66]
大佬我想问一下你那个OCD里面的代码的一些问题，方便回答吗

**Comment by Sped0n** [comment]
> 大佬我想问一下你那个OCD里面的代码的一些问题，方便回答吗
> 
> 

往我[邮箱](realsped0n@outlook.com)发你的联系方式，我有时间会联系你

**Comment by taochenjing** [comment]
3118205300,麻烦大佬了
&nbsp;


在你身边
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月19日(星期三) 中午1:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sped0n/bridget]  标题 (Issue #66)





  
大佬我想问一下你那个OCD里面的代码的一些问题，方便回答吗
  
往我邮箱发你的联系方式，我有时间会联系你
